---
title: "estatistica_multivariada"
output: html_document
date: "2025-09-24"
---

```{r}
library(readxl)
dados <- read_excel("Banco de dados_multivariada.xlsx")
dados
```
```{r}
library(factoextra)

row.names(dados) <- dados$ID
```

```{r}
pca <- prcomp(dados[, 4:17],
              scale = TRUE)
```
```{r}
biplot(pca)
```
```{r}
distancias <- dist(pca$sdev)
dendrograma <- hclust(distancias)
plot(dendrograma)
```
```{r}
summary(pca)
pca$rotation
```
```{r}
grupos <- dados$MANEJO
fviz_pca_biplot(pca,
                col.ind = grupos,
                addEllipses = TRUE,
                legend.title = "Soil management")
```
```{r}
library(readxl)
dadosCanonica <- read_excel("Banco de dados_multivariada.xlsx", 
    sheet = "Correalação Canonica")
dadosCanonica
```
```{r}
X <- dadosCanonica[, 1:3]
Y <- dadosCanonica[, 4:6]
X
Y
```
```{r}
# Correlação canônica
correlacaoCanonica <- cancor(X, Y)
correlacaoCanonica
```
```{r}
library(MVar.pt)

CCA(X, Y, sign = 0.05)
```
```{r}
# Análise discriminante
library(MASS)

dadosAnaliseDiscriminante <- read_excel("Banco de dados_multivariada.xlsx", 
    sheet = "Analise Discriminante")

modeloDiscriminante <- lda(dadosAnaliseDiscriminante$Species ~ dadosAnaliseDiscriminante$Sepal_Length + dadosAnaliseDiscriminante$Sepal_Width + dadosAnaliseDiscriminante$Petal_Length + dadosAnaliseDiscriminante$Petal_Width)

modeloDiscriminante
```
```{r}
predicoesLDA <- predict(modeloDiscriminante)
head(predicoesLDA$class)
table(predicoesLDA$class, dadosAnaliseDiscriminante$Species)
```
```{r}
# PLS_Partial_Least_Mean_Squares
dadosPLS <- read_excel("Banco de dados_multivariada.xlsx", 
    sheet = "PLS")
dadosPLS
```
```{r}
library(pls)

modeloPLS <- plsr(Volume ~ ., validation = "CV", data = dadosPLS)
summary(modeloPLS)
```
```{r}
par(mfrow = c(1, 2))

ncompOneSigma <- selectNcomp(modeloPLS, method = "onesigma", plot = TRUE)
ncompPermut <- selectNcomp(modeloPLS, method = "randomization", plot = TRUE)
```
```{r}
volumeEstimado <- predict(modeloPLS, ncomp = 2, newdata = dadosPLS[, -1])
volumeEstimado
```
```{r}
desvios <- dadosPLS$Volume - volumeEstimado
sum(desvios)
sd(desvios)
shapiro.test(desvios)

library(lmtest)
gqtest(desvios ~ dadosPLS$Volume)

par(mfrow = c(1, 2))
hist(desvios)
boxplot(desvios)
```
```{r}
plot(dadosPLS$Volume, volumeEstimado, xlab = "Dados observados", ylab = "Dados estimados")
lines(x = c(0, 1000), y = c(0, 1000), col = "red")
```
```{r}
RMSEP(modeloPLS)
MSEP(modeloPLS)
R2(modeloPLS)
```

